"use client";

import { useState } from "react";
import Link from "next/link";
import type { Entry, SiteContent } from "../_content/site";

function Field({ label, value, onChange, multiline = false }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean }) {
  return <label className="studio-field"><span>{label}</span>{multiline ? <textarea value={value} onChange={(event) => onChange(event.target.value)} rows={3} /> : <input value={value} onChange={(event) => onChange(event.target.value)} />}</label>;
}

function HeadlineFields({ value, onChange }: { value: { headlineStart: string; headlineEmphasis: string; headlineEnd: string }; onChange: (key: keyof typeof value, next: string) => void }) {
  return <div className="studio-grid studio-grid-three"><Field label="Headline, first part" value={value.headlineStart} onChange={(next) => onChange("headlineStart", next)} /><Field label="Italic highlight" value={value.headlineEmphasis} onChange={(next) => onChange("headlineEmphasis", next)} /><Field label="Headline, last part" value={value.headlineEnd} onChange={(next) => onChange("headlineEnd", next)} /></div>;
}

export default function StudioEditor({ initialContent }: { initialContent: SiteContent }) {
  const [content, setContent] = useState(initialContent);
  const [message, setMessage] = useState("");
  const updateSection = <T extends Exclude<keyof SiteContent, "entries">, K extends keyof SiteContent[T]>(section: T, key: K, value: SiteContent[T][K]) => setContent((current) => ({ ...current, [section]: { ...current[section], [key]: value } }));
  const updateEntry = (index: number, key: keyof Entry, value: string) => setContent((current) => ({ ...current, entries: current.entries.map((entry, entryIndex) => entryIndex === index ? { ...entry, [key]: value } : entry) }));
  const addEntry = () => setContent((current) => ({ ...current, entries: [...current.entries, { number: String(current.entries.length + 1).padStart(2, "0"), date: "SEPTEMBER 08, 2026", title: "A new note", excerpt: "Write a short introduction to this post.", category: "NOTES" }] }));
  const removeEntry = (index: number) => setContent((current) => ({ ...current, entries: current.entries.filter((_, entryIndex) => entryIndex !== index) }));
  const downloadContent = () => {
    const file = new Blob([`${JSON.stringify(content, null, 2)}\n`], { type: "application/json" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(file);
    link.download = "site.json";
    link.click();
    URL.revokeObjectURL(link.href);
    setMessage("Downloaded site.json. Replace app/_content/site.json in GitHub, then commit it to publish your changes.");
  };

  return <main className="studio-shell"><header className="studio-header"><Link className="wordmark" href="/">{content.site.name}</Link><div><span className="studio-status"><i /> Studio</span><a className="studio-view" href="/" target="_blank">View site ↗</a></div></header><div className="studio-layout"><aside className="studio-sidebar"><p>CONTENT STUDIO</p><a href="#site">Site settings</a><a href="#home">Home</a><a href="#writing">Writing</a><a href="#about">About</a><a href="#contact">Contact</a><small>Download your edited content, then replace the matching file in GitHub to publish it.</small></aside><div className="studio-main"><div className="studio-title"><div><p>YOM / CONTENT MANAGER</p><h1>Make it <em>yours.</em></h1></div><button className="studio-save" onClick={downloadContent}>Download changes</button></div>{message && <p className="studio-message">{message}</p>}
    <section className="studio-panel" id="site"><div className="studio-panel-heading"><span>00</span><div><p>SITE SETTINGS</p><h2>Identity & navigation</h2></div></div><div className="studio-grid studio-grid-three"><Field label="Site name" value={content.site.name} onChange={(next) => updateSection("site", "name", next)} /><Field label="Writing link" value={content.site.navWriting} onChange={(next) => updateSection("site", "navWriting", next)} /><Field label="About link" value={content.site.navAbout} onChange={(next) => updateSection("site", "navAbout", next)} /><Field label="Contact link" value={content.site.navContact} onChange={(next) => updateSection("site", "navContact", next)} /><Field label="Status label" value={content.site.signal} onChange={(next) => updateSection("site", "signal", next)} /><Field label="Footer copyright" value={content.site.footerCopyright} onChange={(next) => updateSection("site", "footerCopyright", next)} /></div><div className="studio-grid"><Field label="Footer message" value={content.site.footerTagline} onChange={(next) => updateSection("site", "footerTagline", next)} /><Field label="Browser title" value={content.site.homeTitle} onChange={(next) => updateSection("site", "homeTitle", next)} /></div><Field label="Search description" value={content.site.homeDescription} multiline onChange={(next) => updateSection("site", "homeDescription", next)} /></section>
    <section className="studio-panel" id="home"><div className="studio-panel-heading"><span>01</span><div><p>HOME PAGE</p><h2>First impression</h2></div></div><div className="studio-grid"><Field label="Small label" value={content.home.eyebrow} onChange={(next) => updateSection("home", "eyebrow", next)} /><Field label="Introduction" value={content.home.intro} multiline onChange={(next) => updateSection("home", "intro", next)} /></div><HeadlineFields value={content.home} onChange={(key, next) => updateSection("home", key, next)} /><div className="studio-grid studio-grid-three"><Field label="Topic 1" value={content.home.topics[0] ?? ""} onChange={(next) => updateSection("home", "topics", [next, content.home.topics[1] ?? "", content.home.topics[2] ?? ""])} /><Field label="Topic 2" value={content.home.topics[1] ?? ""} onChange={(next) => updateSection("home", "topics", [content.home.topics[0] ?? "", next, content.home.topics[2] ?? ""])} /><Field label="Topic 3" value={content.home.topics[2] ?? ""} onChange={(next) => updateSection("home", "topics", [content.home.topics[0] ?? "", content.home.topics[1] ?? "", next])} /></div><div className="studio-grid studio-grid-three"><Field label="Writing label" value={content.home.writingLabel} onChange={(next) => updateSection("home", "writingLabel", next)} /><Field label="Writing heading" value={content.home.writingStart} onChange={(next) => updateSection("home", "writingStart", next)} /><Field label="Italic heading" value={content.home.writingEmphasis} onChange={(next) => updateSection("home", "writingEmphasis", next)} /></div><Field label="Archive link" value={content.home.archiveLabel} onChange={(next) => updateSection("home", "archiveLabel", next)} /></section>
    <section className="studio-panel" id="writing"><div className="studio-panel-heading"><span>02</span><div><p>WRITING</p><h2>Your notes</h2></div><button className="studio-add" onClick={addEntry}>+ Add entry</button></div><div className="studio-grid"><Field label="Archive label" value={content.writing.eyebrow} onChange={(next) => updateSection("writing", "eyebrow", next)} /><Field label="Archive introduction" value={content.writing.intro} multiline onChange={(next) => updateSection("writing", "intro", next)} /></div><HeadlineFields value={content.writing} onChange={(key, next) => updateSection("writing", key, next)} />{content.entries.map((entry, index) => <article className="studio-entry" key={`${entry.number}-${index}`}><div className="studio-entry-top"><span>ENTRY {String(index + 1).padStart(2, "0")}</span><button onClick={() => removeEntry(index)}>Remove</button></div><div className="studio-grid studio-grid-three"><Field label="Date" value={entry.date} onChange={(next) => updateEntry(index, "date", next)} /><Field label="Category" value={entry.category} onChange={(next) => updateEntry(index, "category", next)} /><Field label="Title" value={entry.title} onChange={(next) => updateEntry(index, "title", next)} /></div><Field label="Short description" value={entry.excerpt} multiline onChange={(next) => updateEntry(index, "excerpt", next)} /></article>)}</section>
    <section className="studio-panel" id="about"><div className="studio-panel-heading"><span>03</span><div><p>ABOUT PAGE</p><h2>Your story</h2></div></div><div className="studio-grid"><Field label="Small label" value={content.about.eyebrow} onChange={(next) => updateSection("about", "eyebrow", next)} /><Field label="Introduction" value={content.about.intro} multiline onChange={(next) => updateSection("about", "intro", next)} /></div><HeadlineFields value={content.about} onChange={(key, next) => updateSection("about", key, next)} /><div className="studio-grid"><Field label="Card heading" value={content.about.cardTitle} onChange={(next) => updateSection("about", "cardTitle", next)} /><Field label="Contact link label" value={content.about.contactLabel} onChange={(next) => updateSection("about", "contactLabel", next)} /></div><Field label="About paragraph" value={content.about.body} multiline onChange={(next) => updateSection("about", "body", next)} /></section>
    <section className="studio-panel" id="contact"><div className="studio-panel-heading"><span>04</span><div><p>CONTACT PAGE</p><h2>Keep in touch</h2></div></div><div className="studio-grid studio-grid-three"><Field label="Small label" value={content.contact.eyebrow} onChange={(next) => updateSection("contact", "eyebrow", next)} /><Field label="Email address" value={content.contact.email} onChange={(next) => updateSection("contact", "email", next)} /><Field label="Introduction" value={content.contact.intro} multiline onChange={(next) => updateSection("contact", "intro", next)} /></div><HeadlineFields value={content.contact} onChange={(key, next) => updateSection("contact", key, next)} /></section>
    <button className="studio-save studio-save-bottom" onClick={downloadContent}>Download all changes</button></div></div></main>;
}
